### ISSUE TITLE
[QUESTION]: Example for Converting Multi-Page PDF to Images Reactively

### ISSUE THREAD

**Issue by TartanLeGrand** [quarkiverse/quarkus-pdfbox#13]
Hello,

I'm currently working on a project where I need to convert multi-page PDF documents into images reactively, using Quarkus with the SmallRye Mutiny framework. The goal is to process each page of the PDF document in parallel and then combine the resulting images into a single ZIP file for the user to download.

Here's a simplified version of my current implementation:

```kotlin
fun pdf2jpg(@RestForm file: FileUpload): Uni<Response> {
    val inputStream = file.uploadedFile().inputStream().readBytes()
    val doc = Loader.loadPDF(inputStream)
    val renderer = PDFRenderer(doc)
    
    return Multi.createFrom().range(0, doc.numberOfPages)
        .onItem().transformToUniAndMerge { pageIndex ->
            Uni.createFrom().item {
                ByteArrayOutputStream().use { baos ->
                    val image = renderer.renderImageWithDPI(pageIndex, 300f)
                    ImageIO.write(image, "jpg", baos)
                    baos.toByteArray()
                }
            }
        }.collect().asList()
        .onItem().transform { images ->
            ByteArrayOutputStream().use { combinedBaos ->
                ZipOutputStream(combinedBaos).use { zos ->
                    images.forEachIndexed { index, image ->
                        val zipEntry = ZipEntry("page_${index + 1}.jpg")
                        zos.putNextEntry(zipEntry)
                        zos.write(image)
                        zos.closeEntry()
                    }
                }
                combinedBaos.toByteArray()
            }
        }.onItem().transform { zipBytes ->
            doc.close()
            Response.ok(zipBytes).header("Content-Disposition", "attachment; filename=\"images.zip\"").build()
        }
}
```

While this code works, the execution time for a 33-page PDF document is around 7 seconds, which is longer than we'd like. I'm looking for advice on how to optimize this process, potentially by improving parallel processing or any other means to reduce the overall conversion time.

Have you or anyone in the community faced a similar challenge and found a more efficient approach to converting multi-page PDFs to images reactively? Any examples, tips, or guidance you could provide would be greatly appreciated.

Thank you in advance for your help!

**Comment by gastaldi** [comment]
I'd suggest profiling the code to detect potential bottlenecks in the code (https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md#troubleshooting-performance-issues may help). 

One hint: Although it may be faster, storing byte-arrays in memory may be a bad choice memory-wise.

**Comment by gastaldi** [comment]
Also, the code is not async, see https://smallrye.io/smallrye-mutiny/latest/tutorials/transforming-items-asynchronously/#uni-transforming-an-item-into-a-uni for an example

**Comment by gastaldi** [comment]
Closing as this is not a issue, please engage in https://quarkusio.zulipchat.com for any Mutiny/Quarkus discussion
